<?php
/**
 *The main template file Of Advanced Custom Field
 */


if ( function_exists( 'acf_add_local_field_group' ) ):

    acf_add_local_field_group( array(
        'key'                   => 'group_61fa769ecd017',
        'title'                 => 'About Info',
        'fields'                => array(
            array(
                'key'               => 'field_61fa78a807fdf',
                'label'             => 'About Info Thumbnail',
                'name'              => 'about_info_thumbnail',
                'type'              => 'image',
                'instructions'      => 'You can add About Info Thumbnail',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '55',
                    'class' => '',
                    'id'    => '',
                ),
                'return_format'     => 'url',
                'preview_size'      => 'large',
                'library'           => 'all',
                'min_width'         => '',
                'min_height'        => '',
                'min_size'          => '',
                'max_width'         => '',
                'max_height'        => '',
                'max_size'          => '',
                'mime_types'        => '',
            ),
            array(
                'key'               => 'field_61fa7aab07fe0',
                'label'             => 'About Info Title',
                'name'              => 'about_info_title',
                'type'              => 'text',
                'instructions'      => 'You can add About Info Title',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '50',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'maxlength'         => '',
            ),
            array(
                'key'               => 'field_61fa7b3207fe1',
                'label'             => 'About Info Description',
                'name'              => 'about_info_description',
                'type'              => 'text',
                'instructions'      => 'You can add About Info Description',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '50',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'maxlength'         => '',
            ),
            array(
                'key'               => 'field_61fa7c2907fe2',
                'label'             => 'About Info Button Text',
                'name'              => 'about_info_button_text',
                'type'              => 'text',
                'instructions'      => 'You can add About Info Button Text',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '50',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'maxlength'         => '',
            ),
            array(
                'key'               => 'field_61fa7c7007fe3',
                'label'             => 'About Info Button URL',
                'name'              => 'about_info_button_url',
                'type'              => 'url',
                'instructions'      => 'You can add About Info Button URL',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '50',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
            ),
        ),
        'location'              => array(
            array(
                array(
                    'param'    => 'options_page',
                    'operator' => '==',
                    'value'    => 'theme-general-settings',
                ),
            ),
        ),
        'menu_order'            => 0,
        'position'              => 'normal',
        'style'                 => 'default',
        'label_placement'       => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen'        => '',
        'active'                => true,
        'description'           => '',
        'show_in_rest'          => 0,
    ) );

    acf_add_local_field_group( array(
        'key'                   => 'group_61fbb834b3538',
        'title'                 => 'Address',
        'fields'                => array(
            array(
                'key'               => 'field_61fbb85f0f540',
                'label'             => 'Phone Number',
                'name'              => 'phone_number',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '50',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'maxlength'         => '',
            ),
            array(
                'key'               => 'field_61fbb8910f541',
                'label'             => 'Gmail',
                'name'              => 'gmail',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '50',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'maxlength'         => '',
            ),
            array(
                'key'               => 'field_61fbb8b30f542',
                'label'             => 'Office Adress',
                'name'              => 'office_adress',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'maxlength'         => '',
            ),
        ),
        'location'              => array(
            array(
                array(
                    'param'    => 'options_page',
                    'operator' => '==',
                    'value'    => 'acf-options-footer',
                ),
            ),
        ),
        'menu_order'            => 0,
        'position'              => 'normal',
        'style'                 => 'default',
        'label_placement'       => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen'        => '',
        'active'                => true,
        'description'           => '',
        'show_in_rest'          => 0,
    ) );

    acf_add_local_field_group( array(
        'key'                   => 'group_61fb6b5185205',
        'title'                 => 'Case Subject',
        'fields'                => array(
            array(
                'key'               => 'field_61fb6b94e6156',
                'label'             => 'Case Subject',
                'name'              => 'case_subject',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => 'Advisory',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'maxlength'         => '',
            ),
            array(
                'key'               => 'field_6200f78819ffc',
                'label'             => 'Single case contact button text',
                'name'              => 'single_case_contact_button_text',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '50',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'maxlength'         => '',
            ),
            array(
                'key'               => 'field_6200f7b919ffd',
                'label'             => 'Single Case Contact button link',
                'name'              => 'single_case_contact_button_link',
                'type'              => 'url',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '50',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
            ),
        ),
        'location'              => array(
            array(
                array(
                    'param'    => 'post_type',
                    'operator' => '==',
                    'value'    => 'case',
                ),
            ),
        ),
        'menu_order'            => 0,
        'position'              => 'normal',
        'style'                 => 'default',
        'label_placement'       => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen'        => '',
        'active'                => true,
        'description'           => '',
        'show_in_rest'          => 0,
    ) );

    acf_add_local_field_group( array(
        'key'                   => 'group_61fb71f43e3f0',
        'title'                 => 'Client Company Name',
        'fields'                => array(
            array(
                'key'               => 'field_61fb721509dd9',
                'label'             => 'Company Name',
                'name'              => 'company_name',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'maxlength'         => '',
            ),
        ),
        'location'              => array(
            array(
                array(
                    'param'    => 'post_type',
                    'operator' => '==',
                    'value'    => 'testimonial',
                ),
            ),
        ),
        'menu_order'            => 0,
        'position'              => 'acf_after_title',
        'style'                 => 'default',
        'label_placement'       => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen'        => '',
        'active'                => true,
        'description'           => '',
        'show_in_rest'          => 0,
    ) );

    acf_add_local_field_group( array(
        'key'                   => 'group_61fa8690a1d6f',
        'title'                 => 'Contact Info',
        'fields'                => array(
            array(
                'key'               => 'field_61fa86b0f68d6',
                'label'             => 'Contact Info Title',
                'name'              => 'contact_info_title',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '50',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'maxlength'         => '',
            ),
            array(
                'key'               => 'field_61fa86e1f68d7',
                'label'             => 'Contact Info Description',
                'name'              => 'contact_info_description',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '50',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'maxlength'         => '',
            ),
            array(
                'key'               => 'field_61fa86f8f68d8',
                'label'             => 'Contact Info Button Text',
                'name'              => 'contact_info_button_text',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '50',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'maxlength'         => '',
            ),
            array(
                'key'               => 'field_61fa870ff68d9',
                'label'             => 'Contact Info Button URL',
                'name'              => 'contact_info_button_url',
                'type'              => 'url',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '50',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
            ),
        ),
        'location'              => array(
            array(
                array(
                    'param'    => 'options_page',
                    'operator' => '==',
                    'value'    => 'theme-general-settings',
                ),
            ),
        ),
        'menu_order'            => 0,
        'position'              => 'normal',
        'style'                 => 'default',
        'label_placement'       => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen'        => '',
        'active'                => true,
        'description'           => '',
        'show_in_rest'          => 0,
    ) );

    acf_add_local_field_group( array(
        'key'                   => 'group_62026b056d54f',
        'title'                 => 'Contact Page Information',
        'fields'                => array(
            array(
                'key'               => 'field_62026b575e211',
                'label'             => 'Contact Info Title',
                'name'              => 'contact_info_titles',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '50',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'maxlength'         => '',
            ),
            array(
                'key'               => 'field_62026bc65e212',
                'label'             => 'Contact Info Description',
                'name'              => 'contact_info_descriptions',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '50',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'maxlength'         => '',
            ),
            array(
                'key'               => 'field_62026cd25e213',
                'label'             => 'Contact Info Form Button Text',
                'name'              => 'contact_info_form_button_text',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '50',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'maxlength'         => '',
            ),
        ),
        'location'              => array(
            array(
                array(
                    'param'    => 'options_page',
                    'operator' => '==',
                    'value'    => 'theme-general-settings',
                ),
            ),
        ),
        'menu_order'            => 0,
        'position'              => 'normal',
        'style'                 => 'default',
        'label_placement'       => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen'        => '',
        'active'                => true,
        'description'           => '',
        'show_in_rest'          => 0,
    ) );

    acf_add_local_field_group( array(
        'key'                   => 'group_61fb8592017c9',
        'title'                 => 'Copyright Option',
        'fields'                => array(
            array(
                'key'               => 'field_61fb85d71a08d',
                'label'             => 'Copyright Text',
                'name'              => 'copyright_text',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'maxlength'         => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
            ),
        ),
        'location'              => array(
            array(
                array(
                    'param'    => 'options_page',
                    'operator' => '==',
                    'value'    => 'acf-options-footer',
                ),
            ),
        ),
        'menu_order'            => 0,
        'position'              => 'normal',
        'style'                 => 'default',
        'label_placement'       => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen'        => '',
        'active'                => true,
        'description'           => '',
        'show_in_rest'          => 0,
    ) );

    acf_add_local_field_group( array(
        'key'                   => 'group_61f7d68483099',
        'title'                 => 'Header Info',
        'fields'                => array(
            array(
                'key'               => 'field_61f7d6b54c800',
                'label'             => 'Header Address',
                'name'              => 'header_address',
                'type'              => 'text',
                'instructions'      => 'You can write your Office address',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '50',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => 'Dhaka, Bangladesh',
                'placeholder'       => 'Write your address',
                'prepend'           => '',
                'append'            => '',
                'maxlength'         => '',
            ),
            array(
                'key'               => 'field_61f7d73f4c801',
                'label'             => 'Header Email',
                'name'              => 'header_email',
                'type'              => 'email',
                'instructions'      => 'You can write your Email',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '50',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => 'info@bosun.com',
                'placeholder'       => 'Write your Email',
                'prepend'           => '',
                'append'            => '',
            ),
        ),
        'location'              => array(
            array(
                array(
                    'param'    => 'options_page',
                    'operator' => '==',
                    'value'    => 'acf-options-header',
                ),
            ),
        ),
        'menu_order'            => 0,
        'position'              => 'normal',
        'style'                 => 'default',
        'label_placement'       => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen'        => '',
        'active'                => true,
        'description'           => '',
        'show_in_rest'          => 0,
    ) );

    acf_add_local_field_group( array(
        'key'                   => 'group_61f7db2ae453b',
        'title'                 => 'Header Socials',
        'fields'                => array(
            array(
                'key'               => 'field_61f7db420466a',
                'label'             => 'Header Socials',
                'name'              => 'header_socials',
                'type'              => 'repeater',
                'instructions'      => 'If you want, You can add your Socials profile',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'collapsed'         => '',
                'min'               => 0,
                'max'               => 4,
                'layout'            => 'table',
                'button_label'      => 'Add Header Social',
                'sub_fields'        => array(
                    array(
                        'key'               => 'field_61f7dc370466b',
                        'label'             => 'Social URL',
                        'name'              => 'social_url',
                        'type'              => 'url',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array(
                            'width' => '50',
                            'class' => '',
                            'id'    => '',
                        ),
                        'default_value'     => '',
                        'placeholder'       => 'Add Social Link',
                    ),
                    array(
                        'key'               => 'field_61f7dcb90466c',
                        'label'             => 'Social Icon',
                        'name'              => 'social_icon',
                        'type'              => 'select',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array(
                            'width' => '50',
                            'class' => '',
                            'id'    => '',
                        ),
                        'choices'           => array(
                            'fab fa-linkedin-in'   => 'Linkedin',
                            'fab fa-twitter'       => 'Twitter',
                            'fab fa-facebook-f'    => 'Facebook',
                            'fab fa-google-plus-g' => 'Google Plus',
                        ),
                        'default_value'     => false,
                        'allow_null'        => 0,
                        'multiple'          => 0,
                        'ui'                => 1,
                        'ajax'              => 0,
                        'return_format'     => 'array',
                        'placeholder'       => '',
                    ),
                ),
            ),
        ),
        'location'              => array(
            array(
                array(
                    'param'    => 'options_page',
                    'operator' => '==',
                    'value'    => 'acf-options-header',
                ),
            ),
        ),
        'menu_order'            => 0,
        'position'              => 'normal',
        'style'                 => 'default',
        'label_placement'       => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen'        => '',
        'active'                => true,
        'description'           => '',
        'show_in_rest'          => 0,
    ) );

    acf_add_local_field_group( array(
        'key'                   => 'group_61fab70ee0906',
        'title'                 => 'Home Cases	Info',
        'fields'                => array(
            array(
                'key'               => 'field_61fab76e99ca6',
                'label'             => 'Cases Info Title',
                'name'              => 'cases_info_title',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '50',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'maxlength'         => '',
            ),
            array(
                'key'               => 'field_61fab7b199ca7',
                'label'             => 'Cases Info Description',
                'name'              => 'cases_info_description',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '50',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'maxlength'         => '',
            ),
            array(
                'key'               => 'field_61fab7cb99ca8',
                'label'             => 'Cases Info Button Text',
                'name'              => 'cases_info_button_text',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '50',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'maxlength'         => '',
            ),
            array(
                'key'               => 'field_61fab7fe99ca9',
                'label'             => 'Cases Info Button URL',
                'name'              => 'cases_info_button_url',
                'type'              => 'url',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '50',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
            ),
        ),
        'location'              => array(
            array(
                array(
                    'param'    => 'options_page',
                    'operator' => '==',
                    'value'    => 'theme-general-settings',
                ),
            ),
        ),
        'menu_order'            => 0,
        'position'              => 'normal',
        'style'                 => 'default',
        'label_placement'       => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen'        => '',
        'active'                => true,
        'description'           => '',
        'show_in_rest'          => 0,
    ) );

    acf_add_local_field_group( array(
        'key'                   => 'group_61f91dbfdb474',
        'title'                 => 'Slider Info',
        'fields'                => array(
            array(
                'key'               => 'field_61f91dc7e4482',
                'label'             => 'Slider Subtitle',
                'name'              => 'slider_subtitle',
                'type'              => 'text',
                'instructions'      => 'You can add Slider subtitle',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'maxlength'         => '',
            ),
            array(
                'key'               => 'field_61f91e22e4483',
                'label'             => 'Slider Button text',
                'name'              => 'slider_button_text',
                'type'              => 'text',
                'instructions'      => 'You can add Slider Button',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '50',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => 'Add Slider Button Name',
                'prepend'           => '',
                'append'            => '',
                'maxlength'         => '',
            ),
            array(
                'key'               => 'field_61f91e7ee4484',
                'label'             => 'Slider Button URL',
                'name'              => 'slider_button_url',
                'type'              => 'url',
                'instructions'      => 'You can add slider button URL',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '50',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => 'Write Button URL',
            ),
        ),
        'location'              => array(
            array(
                array(
                    'param'    => 'post_type',
                    'operator' => '==',
                    'value'    => 'slider',
                ),
            ),
        ),
        'menu_order'            => 0,
        'position'              => 'normal',
        'style'                 => 'default',
        'label_placement'       => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen'        => '',
        'active'                => true,
        'description'           => '',
        'show_in_rest'          => 0,
    ) );

    acf_add_local_field_group( array(
        'key'                   => 'group_61fb8bfba2592',
        'title'                 => 'Social Info',
        'fields'                => array(
            array(
                'key'               => 'field_61fb8c24e2273',
                'label'             => 'Social Links',
                'name'              => 'social_links',
                'type'              => 'repeater',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'collapsed'         => '',
                'min'               => 0,
                'max'               => 4,
                'layout'            => 'table',
                'button_label'      => 'Add Social Profile',
                'sub_fields'        => array(
                    array(
                        'key'               => 'field_61fb8c93e2274',
                        'label'             => 'Social Link',
                        'name'              => 'social_link',
                        'type'              => 'url',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array(
                            'width' => '50',
                            'class' => '',
                            'id'    => '',
                        ),
                        'default_value'     => '',
                        'placeholder'       => '',
                    ),
                    array(
                        'key'               => 'field_61fb8cb6e2275',
                        'label'             => 'Social Icon',
                        'name'              => 'social_icon',
                        'type'              => 'select',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array(
                            'width' => '50',
                            'class' => '',
                            'id'    => '',
                        ),
                        'choices'           => array(
                            'fab fa-facebook-square'  => 'Facebook',
                            'fab fa-twitter-square'   => 'Twitter',
                            'fab fa-linkedin'         => 'Linkedin',
                            'fab fa-pinterest-square' => 'Pinterest',
                        ),
                        'default_value'     => false,
                        'allow_null'        => 0,
                        'multiple'          => 0,
                        'ui'                => 0,
                        'return_format'     => 'value',
                        'ajax'              => 0,
                        'placeholder'       => '',
                    ),
                ),
            ),
            array(
                'key'               => 'field_61fbb4e298293',
                'label'             => 'Title info',
                'name'              => 'title_info',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'maxlength'         => '',
            ),
        ),
        'location'              => array(
            array(
                array(
                    'param'    => 'options_page',
                    'operator' => '==',
                    'value'    => 'acf-options-footer',
                ),
            ),
        ),
        'menu_order'            => 0,
        'position'              => 'normal',
        'style'                 => 'default',
        'label_placement'       => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen'        => '',
        'active'                => true,
        'description'           => '',
        'show_in_rest'          => 0,
    ) );

    acf_add_local_field_group( array(
        'key'                   => 'group_61fb7a44a0bb2',
        'title'                 => 'Star Rating',
        'fields'                => array(
            array(
                'key'               => 'field_61fb7a6eef8a5',
                'label'             => '5 Star',
                'name'              => 'five_star',
                'type'              => 'true_false',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '50',
                    'class' => '',
                    'id'    => '',
                ),
                'message'           => '',
                'default_value'     => 0,
                'ui'                => 0,
                'ui_on_text'        => '',
                'ui_off_text'       => '',
            ),
            array(
                'key'               => 'field_61fb7df4ef8a6',
                'label'             => '4 Star',
                'name'              => 'four_star',
                'type'              => 'true_false',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '50',
                    'class' => '',
                    'id'    => '',
                ),
                'message'           => '',
                'default_value'     => 0,
                'ui'                => 0,
                'ui_on_text'        => '',
                'ui_off_text'       => '',
            ),
            array(
                'key'               => 'field_61fb7e88ef8a7',
                'label'             => '3 Star',
                'name'              => 'three_star',
                'type'              => 'true_false',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '50',
                    'class' => '',
                    'id'    => '',
                ),
                'message'           => '',
                'default_value'     => 0,
                'ui'                => 0,
                'ui_on_text'        => '',
                'ui_off_text'       => '',
            ),
            array(
                'key'               => 'field_61fb7e9def8a8',
                'label'             => '2 Star',
                'name'              => 'two_star',
                'type'              => 'true_false',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '50',
                    'class' => '',
                    'id'    => '',
                ),
                'message'           => '',
                'default_value'     => 0,
                'ui'                => 0,
                'ui_on_text'        => '',
                'ui_off_text'       => '',
            ),
        ),
        'location'              => array(
            array(
                array(
                    'param'    => 'post_type',
                    'operator' => '==',
                    'value'    => 'testimonial',
                ),
            ),
        ),
        'menu_order'            => 0,
        'position'              => 'normal',
        'style'                 => 'default',
        'label_placement'       => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen'        => '',
        'active'                => true,
        'description'           => '',
        'show_in_rest'          => 0,
    ) );

    acf_add_local_field_group( array(
        'key'                   => 'group_61fa8e9ecea18',
        'title'                 => 'Team Member Position',
        'fields'                => array(
            array(
                'key'               => 'field_61fa8ec46a604',
                'label'             => 'Add Team Member Position',
                'name'              => 'add_team_member_position',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '50',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'maxlength'         => '',
            ),
        ),
        'location'              => array(
            array(
                array(
                    'param'    => 'post_type',
                    'operator' => '==',
                    'value'    => 'team',
                ),
            ),
        ),
        'menu_order'            => 0,
        'position'              => 'normal',
        'style'                 => 'default',
        'label_placement'       => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen'        => '',
        'active'                => true,
        'description'           => '',
        'show_in_rest'          => 0,
    ) );

endif;